# Representing Data and Engineering Features

In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set_theme()
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

## Categorical Variables - Adult incomes in the US

**Task**: Predict whether a worker has an income of over $\text{\$}$50,000 or under $\text{\$}$50,000.

In [25]:
# Import dataset
from sklearn.datasets import fetch_openml
adult = fetch_openml(name='adult', data_home='~/IBM-Data-Science-Specialization/Course-9_Machine-Learning/data/adult', version=2)

In [26]:
# Show first 10 entries of data
adult.data.head(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States
6,29,NaN,227026,HS-grad,9,Never-married,NaN,Unmarried,Black,Male,0,0,40,United-States
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States

The task is a classification task, but it is also possible to predict the exact income (a regression task). That is much more difficult, and the classification task is interesting on its own.

In [27]:
# Data types of the features
adult.data.dtypes

age                  int64
workclass         category
fnlwgt               int64
education         category
education-num        int64
marital-status    category
occupation        category
relationship      category
race              category
sex               category
capital-gain         int64
capital-loss         int64
hours-per-week       int64
native-country    category
dtype: object

## One-Hot-Encoding, aka One-Out-of-N Encoding, aka Dummy Variables

I will use **one-hot-encoding**, a.k.a. **dummy variables** to represent the above categorical features. To be able to follow the book's demonstration, I will drop some of the columns the authors did not include.

In [28]:
adult.data.drop(columns=['fnlwgt', 'education-num', 'marital-status', 'relationship', 'race', 'capital-gain', 'capital-loss', 'native-country'],
       inplace=True)

In [29]:
adult.data.head()

   age  workclass     education         occupation     sex  hours-per-week
0   25    Private          11th  Machine-op-inspct    Male              40
1   38    Private       HS-grad    Farming-fishing    Male              50
2   28  Local-gov    Assoc-acdm    Protective-serv    Male              40
3   44    Private  Some-college  Machine-op-inspct    Male              40
4   18        NaN  Some-college                NaN  Female              30

In one-hot encoding, a new feature is created for each category, and the value of the new feature is 1 for samples that belong to the corresponding category, and 0 otherwise.

The Pandas function `get_dummies()` automatically does the encoding for all categorical columns in a Dataframe.

In [46]:
X = pd.get_dummies(adult.data, dtype=int)

In [47]:
print("Original features \n", list(adult.data.columns))
print("Encoded features \n", list(X.columns))

Original features
 ['age', 'workclass', 'education', 'occupation', 'sex', 'hours-per-week']
Encoded features
 ['age', 'hours-per-week', 'workclass_Federal-gov', 'workclass_Local-gov', 'workclass_Never-worked', 'workclass_Private', 'workclass_Self-emp-inc', 'workclass_Self-emp-not-inc', 'workclass_State-gov', 'workclass_Without-pay', 'education_10th', 'education_11th', 'education_12th', 'education_1st-4th', 'education_5th-6th', 'education_7th-8th', 'education_9th', 'education_Assoc-acdm', 'education_Assoc-voc', 'education_Bachelors', 'education_Doctorate', 'education_HS-grad', 'education_Masters', 'education_Preschool', 'education_Prof-school', 'education_Some-college', 'occupation_Adm-clerical', 'occupation_Armed-Forces', 'occupation_Craft-repair', 'occupation_Exec-managerial', 'occupation_Farming-fishing', 'occupation_Handlers-cleaners', 'occupation_Machine-op-inspct', 'occupation_Other-service', 'occupation_Priv-house-serv', 'occupation_Prof-specialty', 'occupation_Protective-serv', 'occupation_Sales', 'occupation_Tech-support', 'occupation_Transport-moving', 'sex_Female', 'sex_Male']

Data has now been prepared in a form that is appropriate for use with Scikit-learn. We can now proceed to training a classifier on the data.

In [48]:
X = X.to_numpy()
y = adult.target.to_numpy()
print('X shape:', X.shape, 'y shape:', y.shape)

X shape: (48842, 42) y shape: (48842,)

There are two classes in the dataset, so a binary classifier such as logistic regression is appropriate.

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
logreg_score = LogisticRegression().fit(X_train,y_train).score(X_test,y_test)
print(f'Test score: {logreg_score:.2f}')

Test score: 0.81

## Numbers Can Encode Categoricals